name: Build and Test
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      # Should be replaced by true E2E test which check the outputs
      - name: Run basic scenarios
        run: |
          yarn start:dev --alertRpsThreshold 1
          yarn start:dev --logFilePath resources/trigger_alert.txt
